- Load a text dataset

Perform preprocessing:

- Tokenization.

- Stopword removal.

- Lemmatization & stemming.

- Compare outputs of lemmatization vs. stemming with examples.

In [ ]:
# importing the necessary libraries
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import word_tokenize

In [ ]:
# Download necessary resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
df = pd.read_json("hf://datasets/heegyu/news-category-dataset/data.json", lines=True) # loading dataset

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [ ]:
df.shape # checking for the shape of the dataset

(209527, 6)

In [ ]:
df.isnull().sum() # checking for the missing values

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

In [ ]:
df.duplicated().sum() # checking for the duplicated values

np.int64(13)

In [ ]:
df.drop_duplicates(inplace=True) # dropping the duplicated values

In [ ]:
texts = df['headline'].sample(5, random_state=42)  # pick 5 random headlines to demonstrate

In [ ]:
texts

177384           Igloofest: Montreal's Wildest Winter Party
25625     Steve Bannon: Chris Christie's Lack Of Loyalty...
56836     Trump Doubles Down On Personal Attack Against ...
114376                             Miracles Work Everywhere
50392     3,800-Year-Old Ancient 'Thinking Person' Statu...
Name: headline, dtype: object

# Preprocessing

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

In [ ]:
# function for the data preprocessing

def preprocess(text):
    # Tokenization
    tokens = word_tokenize(text.lower())
    # Remove stopwords and non-alphabetic words
    tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
    return tokens

In [ ]:
# Compare Lemmatization vs Stemming
for i, text in enumerate(texts, 1):
    tokens = preprocess(text)
    lemmatized = [lemmatizer.lemmatize(word) for word in tokens]
    stemmed = [stemmer.stem(word) for word in tokens]


    print("Original text: ", text)
    print("Lemmatized: ", lemmatized)
    print("Stemmed: ", stemmed)
    print("tokenized", tokens)

Original text:  Igloofest: Montreal's Wildest Winter Party
Lemmatized:  ['igloofest', 'montreal', 'wildest', 'winter', 'party']
Stemmed:  ['igloofest', 'montreal', 'wildest', 'winter', 'parti']
tokenized ['igloofest', 'montreal', 'wildest', 'winter', 'party']
Original text:  Steve Bannon: Chris Christie's Lack Of Loyalty Cost Him Cabinet Consideration
Lemmatized:  ['steve', 'bannon', 'chris', 'christie', 'lack', 'loyalty', 'cost', 'cabinet', 'consideration']
Stemmed:  ['steve', 'bannon', 'chri', 'christi', 'lack', 'loyalti', 'cost', 'cabinet', 'consider']
tokenized ['steve', 'bannon', 'chris', 'christie', 'lack', 'loyalty', 'cost', 'cabinet', 'consideration']
Original text:  Trump Doubles Down On Personal Attack Against The Federal Reserve
Lemmatized:  ['trump', 'double', 'personal', 'attack', 'federal', 'reserve']
Stemmed:  ['trump', 'doubl', 'person', 'attack', 'feder', 'reserv']
tokenized ['trump', 'doubles', 'personal', 'attack', 'federal', 'reserve']
Original text:  Miracles Work Everywhere
Lemmatized:  ['miracle', 'work', 'everywhere']
Stemmed:  ['miracl', 'work', 'everywher']
tokenized ['miracles', 'work', 'everywhere']
Original text:  3,800-Year-Old Ancient 'Thinking Person' Statuette Unearthed
Lemmatized:  ['ancient', 'person', 'statuette', 'unearthed']
Stemmed:  ['ancient', 'person', 'statuett', 'unearth']
tokenized ['ancient', 'person', 'statuette', 'unearthed']